// src/report/coverPage.js

import logo from "../assets/logo.png";
import { formatDateTime } from "./pdfHelpers";

function imageToBase64(src) {
    return new Promise((resolve) => {

        const img = new Image();

        img.crossOrigin = "Anonymous";

        img.onload = () => {

            const canvas = document.createElement("canvas");

            canvas.width = img.width;
            canvas.height = img.height;

            const ctx = canvas.getContext("2d");

            ctx.drawImage(img, 0, 0);

            resolve(canvas.toDataURL("image/png"));

        };

        img.src = src;

    });
}

export async function drawCoverPage(doc) {

    const logoImage = await imageToBase64(logo);

    const { date, time } = formatDateTime();

    // Background
    doc.setFillColor(7, 26, 45);
    doc.rect(0, 0, 210, 297, "F");

    // Decorative top bar
    doc.setFillColor(0, 184, 255);
    doc.rect(0, 0, 210, 6, "F");

    // Logo
    doc.addImage(
        logoImage,
        "PNG",
        65,
        18,
        80,
        55
    );

    // Main Title
    doc.setFont("helvetica", "bold");
    doc.setFontSize(27);
    doc.setTextColor(255, 255, 255);

    doc.text(
        "Security Incident Report",
        105,
        105,
        {
            align: "center"
        }
    );

    // Divider
    doc.setDrawColor(0, 184, 255);
    doc.setLineWidth(0.8);
    doc.line(45, 112, 165, 112);

    // Subtitle
    doc.setFontSize(16);
    doc.setTextColor(0, 184, 255);

    doc.text(
        "Machine Learning Powered",
        105,
        126,
        {
            align: "center"
        }
    );

    doc.text(
        "DDoS Detection & Prevention Platform",
        105,
        136,
        {
            align: "center"
        }
    );

    // Prepared For
    doc.setFontSize(12);
    doc.setTextColor(180, 180, 180);

    doc.text(
        "Prepared For",
        105,
        165,
        {
            align: "center"
        }
    );

    doc.setFontSize(18);
    doc.setTextColor(255, 255, 255);

    doc.text(
        "System Administrator",
        105,
        176,
        {
            align: "center"
        }
    );

    // Document Information
    doc.setFontSize(12);
    doc.setTextColor(200);

    doc.text(
        "Version 1.0",
        105,
        198,
        {
            align: "center"
        }
    );

    doc.text(
        date,
        105,
        208,
        {
            align: "center"
        }
    );

    doc.text(
        time,
        105,
        218,
        {
            align: "center"
        }
    );

    // Document ID
    const documentId = `DDG-${new Date().getFullYear()}-${Date.now()
        .toString()
        .slice(-6)}`;

    doc.setFontSize(10);
    doc.setTextColor(170);

    doc.text(
        `Document ID : ${documentId}`,
        105,
        232,
        {
            align: "center"
        }
    );

    // Confidential
    doc.setFontSize(11);
    doc.setTextColor(255, 70, 70);

    doc.text(
        "CONFIDENTIAL",
        105,
        260,
        {
            align: "center"
        }
    );

    // Footer
    doc.setFontSize(9);
    doc.setTextColor(180);

    doc.text(
        "Generated by DDoS Guard",
        105,
        272,
        {
            align: "center"
        }
    );

    doc.text(
        "Machine Learning Powered DDoS Detection & Prevention Platform",
        105,
        279,
        {
            align: "center"
        }
    );
}