import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import logo from "../assets/logo.png";
function imageToBase64(src) {
    return new Promise((resolve) => {
        const img = new Image();

        img.crossOrigin = "Anonymous";

        img.onload = () => {

            const canvas = document.createElement("canvas");

            canvas.width = img.width;

            canvas.height = img.height;

            const ctx = canvas.getContext("2d");

            ctx.drawImage(img, 0, 0);

            resolve(canvas.toDataURL("image/png"));

        };

        img.src = src;

    });
}
export default async function generatePDF(analytics){
const logoImage = await imageToBase64(logo);
    const doc = new jsPDF();

    const date = new Date().toLocaleString();

    // Header
    // Cover Background

doc.setFillColor(7, 26, 45);

doc.rect(0, 0, 210, 297, "F");

// Logo

doc.addImage(

    logoImage,

    "PNG",

    55,

    28,

    100,

    70

);

// Main Title

doc.setTextColor(255,255,255);

doc.setFontSize(28);

doc.setFont(

    "helvetica",

    "bold"

);

doc.text(

    "Security Incident Report",

    105,

    125,

    {

        align:"center"

    }

);

// Subtitle

doc.setFontSize(16);

doc.setTextColor(0,184,255);

doc.text(

    "Machine Learning Powered",

    105,

    142,

    {

        align:"center"

    }

);

doc.text(

    "DDoS Detection & Prevention Platform",

    105,

    152,

    {

        align:"center"

    }

);

// Version

doc.setFontSize(13);

doc.setTextColor(210,210,210);

doc.text(

    "Version 1.0",

    105,

    176,

    {

        align:"center"

    }

);

// Date

doc.text(

    new Date().toLocaleString(),

    105,

    186,

    {

        align:"center"

    }

);

// Confidential

doc.setFontSize(11);

doc.setTextColor(255,80,80);

doc.text(

    "CONFIDENTIAL",

    105,

    260,

    {

        align:"center"

    }

);
doc.addPage();

    // Reset text color
    doc.setTextColor(0, 0, 0);

    let y = 40;

    doc.setFontSize(16);
    doc.text("Executive Summary", 14, y);

    y += 10;

    doc.setFontSize(11);
    doc.text(`Generated : ${date}`, 14, y);

    y += 10;

    autoTable(doc, {

        startY: y,

        head: [["Metric", "Value"]],

        body: [

            ["Total Incidents", analytics.totalIncidents],

            ["Critical", analytics.severityDistribution?.critical || 0],

            ["High", analytics.severityDistribution?.high || 0],

            ["Medium", analytics.severityDistribution?.medium || 0],

            ["Low", analytics.severityDistribution?.low || 0],

            ["Average Latency", `${analytics.averageLatency} ms`],

            ["Detection Effectiveness", `${analytics.averageEffectiveness}%`]

        ],

        headStyles: {

            fillColor: [22, 33, 62]

        }

    });

    autoTable(doc, {

        startY: doc.lastAutoTable.finalY + 12,

        head: [["Recommendations"]],

        body: [

            ["Continue monitoring abnormal traffic."],

            ["Review firewall rules regularly."],

            ["Keep ML model updated with new traffic."],

            ["Investigate repeated attacker IPs."],

            ["Enable real-time notifications."]

        ],

        headStyles: {

            fillColor: [0, 150, 136]

        }

    });

    doc.setFontSize(10);

    doc.text(

        "Generated by DDoS Guard Security Platform",

        14,

        285

    );

    doc.save(

        `DDoS_Guard_Report_${Date.now()}.pdf`

    );

}